import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import MyNavbar from "@/components/navbar/MyNavbar";
import "./globals.css";
import { Navbar } from "@nextui-org/react";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <Providers>
  
      <body className={`${inter.className}  text-foreground bg-background`}>
      <Toaster position="top-right" richColors={true} />
        {children}  
         </body>
      </Providers>
    </html>
  );
}
